modLoader = "javafml"
loaderVersion = "[${neoforgeloaderversion},)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbfiltersystem"
version = "${version}"
displayName = "FTB Filter System"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-filter-system"
authors = "FTB Team"
description = '''
Smart and highly configurable item filtering system with useful GUI configuration
'''
#logoFile = ""

[[dependencies.ftbfiltersystem]]
modId = "neoforge"
type = "required"
versionRange = "${neoforgeversionrange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "minecraft"
type = "required"
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "architectury"
type = "required"
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "ftblibrary"
type = "required"
versionRange = "[${ftblibraryversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "jei"
type = "optional"
versionRange = "[19.5.0.40,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "ftbxmodcompat"
type = "optional"
versionRange = "[21.1.7,)"
side = "BOTH"
